name: Terraform_Kube

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: navneet78/myapp_terrakube
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: DockerHub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Build and Push image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Copy Terraform files to remote VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VM_PUBLIC_IP}}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_PRIVATE_KEY }}
        source: "./terraform/"
        target:"/home/${{ secrets.VM_USER }}/project/terraform"

    - name: SSH and Run Terraform Apply
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_PUBLIC_IP }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.VM_USERNAME }}/project/terraform
          export TF_VAR_image_tag=${{ env.IMAGE_TAG }}
          terraform init -input=false
          terraform apply -auto-approve -input=false
